### ISSUE TITLE
3 phase enhancement port

### ISSUE THREAD

**Issue by Glazzanz** [FredM67/PVRouter-1-phase#1]
Hi Fred

I’ve stumbled across your 3phase PVRouter that appears to be just what I am looking for with the inputs to force full power and advise of off peak…

Any chance of these features been ported to this single phase version?

thanks

**Comment by FredM67** [comment]
Hi,

There's no problem to port that to the single phase router... as long as there're still 2 free inputs !
That's for the hardware part.
On the software side, the standard program must be extended.

Do you already own a router from Robin Emley?

Fred


Envoyé à partir d’Outlook<http://aka.ms/weboutlook>

________________________________
De : Glazzanz ***@***.***>
Envoyé : mercredi 19 mai 2021 12:51
À : FredM67/PVRouter-Single ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [FredM67/PVRouter-Single] 3 phase enhancement port (#1)


Hi Fred

I’ve stumbled across your 3phase PVRouter that appears to be just what I am looking for with the inputs to force full power and advise of off peak…

Any chance of these features been ported to this single phase version?

thanks

**Comment by Glazzanz** [comment]
Hi

I am running on Arduino mega, and as such have ample spare inputs.

thanks

**Comment by FredM67** [comment]
Okay... So what do you want from me exactly?
I can add almost any functionalities in the program, but I need to know what exactly 😎

**Comment by Glazzanz** [comment]
Hi Fred

Im wanting to add an element of control to the pv router, an option where I can disable/prevent any power getting exported (an input that forces the SSR to be off) and an option where I can force hot water to heat (an input than forces the SSR to be on).

I'm looking at using a ESP32 to control these inputs.

Thanks
David

**Comment by FredM67** [comment]
Ok... To force the SSR to be off, the easiest way is the wire the command cable of the SSR through a relay. If the relay is open, then the SSR will never fire.
To force the SSR on, that's almost the same. We'd use a relay connected to one input of the Arduino plus a small modification in the program. On Amazon or so, you can find for just a couple of $/€ smart relays (https://www.amazon.co.uk/Newgoal-2-Channel-Momentary-Adjustable-Compatible/dp/B08BJLTG76/ref=sr_1_1?dchild=1&keywords=B08BJLTG76&qid=1621486246&sr=8-1)

**Comment by Glazzanz** [comment]
Thanks. 

The ideal of using the ESP32 was to also connect to the parse the serial output of the Arduino, and pass information back to “Home Assistant” as to the status of the diverter.

For this reason it would be ideal that the diverter itself knew it has been disabled.

I actually need to check to see if your work is based on the “with logging” code from mk2pvrouter

**Comment by FredM67** [comment]
My code matches exactly the original code of Robin. It could just be, that I'm one/two updates behind. I regularly check if Robin has made some changes and change my code accordingly.

**Comment by Glazzanz** [comment]
Yes, sorry I hadn’t looked at your code to see if you were logging info to the serial interface.  This isn’t present in all of Robin’s code.

Would the two inputs discussed be something you would be willing to implement?

thanks

**Comment by FredM67** [comment]
Sure I can implement this in my code... Do you already know which pins you'll use for that?

**Comment by Glazzanz** [comment]
Not at this stage sorry, but if it could be defined as a variable that would be great.

**Comment by FredM67** [comment]
Okay... I'll try to get it implemented ASAP.
Note: I won't be able to test it in real, because I only have a 3-phase router ! But I'll try to get a working code right on the first try ;-)

**Comment by Glazzanz** [comment]
Thanks.  More than happy to test.  Thanks again.

**Comment by Glazzanz** [comment]
Hi Fred, question for you.. I notice in the 3phase version you have:

NUM_OF_PHASES
NO_OF_DUMPLOADS

If these were both changes to 2, would that essentially work as a single phase diverter?

**Comment by FredM67** [comment]
A single phase diverter has only ONE phase, so you'd need to set NUM_OF_PHASES to 1. Even both programs are similar (single and 3-phases), the single phase version is doing all the calculations most of the time with integers instead of float.
The parameter NO_OF_DUMLOADS is to be set to the number of loads that are connected. It has nothing to do with single or 3 phase.

**Comment by Glazzanz** [comment]
Sorry, what I mean’t was would the 3 phase version work on single phase, with NUM_OF_PHASES set to one?

rather than having to maintain two codes based?

**Comment by FredM67** [comment]
Well, there's a major difference between both codes:

- For a single phase router, a display is present to count and show the daily diverted energy.

- In the 3-phase version, there's no display because there's no free AC/DC converter left (6 on the arduino), so it's impossible to mount a 2nd CT to measure the diverted energy.

In the single phase, there's a prediction feature that allows to take decisions one sinusoidal before. This is needed specially for the Linky (in France).
On a 3-phase system, since we needed to sum up the 3-phase, even the Linky 3-phase has less "precision" than the single-phase version.

**Comment by Glazzanz** [comment]
Ok, thanks for your explanation.  Understand the differences between them now.

In my case, I don’t plan to put a display on the unit itself (as the units not in an ideal place to look at) rather plan to capture the json output to the esp, and send that to home assistant, where a virtual screen will be displayed.

Understand that my use case is somewhat unique.

Thanks again
david@hb.net.nz // +64-21-244-9263

**Comment by FredM67** [comment]
Your case isn't unique. If you look at the 3-phase code, you'll see a function that writes json on the serial instead of "pure text".
If you want json, I can add that too, but I'll need to know what to send, how (key names, structure,...)

**Comment by FredM67** [comment]
Thx for your friendly support 😎

**Comment by Glazzanz** [comment]
Thanks.  Yes the json output would be great.

I think it would be good to have the following:

Load_mains (Watts)
Load_diverted (Watts)
SSR1_status (on/off)
_SSR2_status (on/off)_
Force_on_1 (true/false)
_Force_on_2 (true/false)_
Force_off_1 (true/false)
_Force_off_2 (true/false)_
_Temp_ 

Items in italic would be be options to be connected.

It would be good to have an input that can invert the priority of the SSR.  For example by default any diverted power goes to SSR1, when we still have excess power we start also diverting to SSR2.  It would be good to have an input that inverts this - so SSR2 is primary and SSR1 is secondary.

Thanks

**Comment by FredM67** [comment]
No problem for all of that... so now I need to find free time :D

**Comment by Glazzanz** [comment]
Thank you.  No free time I can relate too :-)

**Comment by FredM67** [comment]
Hi,
I've started to implement your whishes....
First question, what do you mean with "SSR1_status" (on/off)?

**Comment by Glazzanz** [comment]
It is an indication if the SSR output was on or off.  

Cheers

**Comment by FredM67** [comment]
> It is an indication if the SSR output was on or off.
> 
> Cheers

Well ok, but since the output state can change like 50 times per second, this data is somehow useless.
For someone else (3-phase), I've calculated the average percent of time that the load was ON during 5 seconds... would it be useful for you?

**Comment by Glazzanz** [comment]
Yes, that sounds great.  Thank you.

**Comment by FredM67** [comment]
Another question :D
You want for each load a "force on" and a "force off"....What should happen if both are set to true? which one wins?

**Comment by Glazzanz** [comment]
> What should happen if both are set to true? which one wins?

Both would be turned on.  Basically this would be used to bypass the logic, for example if hot water is cold, and we want to heat it, etc.

Thanks

**Comment by FredM67** [comment]
> > What should happen if both are set to true? which one wins?
> 
> Both would be turned on. Basically this would be used to bypass the logic, for example if hot water is cold, and we want to heat it, etc.
> 
> Thanks

No, I mean, for each load, you want a pin to force to on (heating), and also a pin to force to off (in fact disable the load)...
If both force_on AND force_off are true, which one wins?

**Comment by Glazzanz** [comment]
Sorry, force off should win.

Thanks
David

**Comment by Glazzanz** [comment]
Sorry, I have another question for you. I'm trying to understand why some of the SSR outputs are active high, and others are active low.  

In my case I would to enable the SSR by setting the output to high (supplying 5v).

To achieve this, would it be as simple as changing line 505 from:

digitalWrite(physicalLoad_0_pin, (uint8_t_physicalLoadState[0]);

to (adding the ! before (uint8

digitalWrite(physicalLoad_0_pin, **!**(uint8_t_physicalLoadState[0]);

Thanks

**Comment by FredM67** [comment]
That's exactly what you mean.
If you look at the 3-phase PCB, you'll see for D3 till D9 3 pins, one Vcc, one in the middle and one GND.
If you  connect between Gnd and the middle, the output is active high (you'll get Vcc in the middle) and if you connect between Vcc and the middle, the output is active low (Gnd on the middle when calling digitalwrite with 0).

**Comment by eogmau** [comment]
> That's exactly what you mean. If you look at the 3-phase PCB, you'll see for D3 till D9 3 pins, one Vcc, one in the middle and one GND. If you connect between Gnd and the middle, the output is active high (you'll get Vcc in the middle) and if you connect between Vcc and the middle, the output is active low (Gnd on the middle when calling digitalwrite with 0).

Hi Fred,
I am looking to implement full-power forcing on my single load PV router from Robin which is running Mk2_fasterControl_3 sketch.
Can the code for full-power forcing and Json logging from PVRouter-3-phase ported to the single phase board?

Thanks

**Comment by FredM67** [comment]
> > That's exactly what you mean. If you look at the 3-phase PCB, you'll see for D3 till D9 3 pins, one Vcc, one in the middle and one GND. If you connect between Gnd and the middle, the output is active high (you'll get Vcc in the middle) and if you connect between Vcc and the middle, the output is active low (Gnd on the middle when calling digitalwrite with 0).
> 
> Hi Fred,
> I am looking to implement full-power forcing on my single load PV router from Robin which is running Mk2_fasterControl_3 sketch.
> Can the code for full-power forcing and Json logging from PVRouter-3-phase ported to the single phase board?
> 
> Thanks

Hi,
For sure, you can take portions of 3-phase code and integrate it to the single phase.
Just keep in mind that a couple of things are different like pin assignment, active-low VS active-high,....
If there's the need to fully "upgrade" the single phase code so it matches the functionalities and architecture of the 3-phase, I can do that.... Or you fork the repos, implement it your self and create a merge/pull request to the original repos.
I'm quite busy with a new functionality for the 3-phase (diversion through one or more relays), so any help'll be greatly thankfully appreciated.
